# Generated by Django 4.2.17 on 2025-01-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category_alter_product_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_data',
            field=models.TextField(default='{}'),
        ),
    ]
