# Generated by Django 4.2.7 on 2025-10-31 14:54

from django.db import migrations, models
import django.db.models.deletion
import store.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to=store.models.Product.get_download_file),
        ),
        migrations.AddField(
            model_name='product',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='store/qr_codes/')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='downloadable', to='store.orderitem')),
            ],
        ),
    ]
