# Generated by Django 4.2.7 on 2025-11-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_download_file_product_is_downloadable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, help_text="Required only if 'Downloadable' is checked", null=True, upload_to='downloads/'),
        ),
    ]
