# Generated by Django 4.2.7 on 2025-12-29 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_product_download_file_product_is_downloadable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='verification_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID único de la transacción generado por el proveedor de pago (ej. PayPal ID).', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('MANUAL', 'Aprobación Manual/Crédito')], default='PAYPAL', help_text='Método de pago utilizado para la orden.', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from the store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, help_text='Obligatorio solo si el producto es descargable', null=True, upload_to=store.models.Product.get_download_file),
        ),
    ]
