# Generated by Django 4.2.7 on 2025-12-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_downloadable_verification_url_order_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_downloadable',
            new_name='is_digital',
        ),
    ]
