# Generated by Django 4.2.7 on 2025-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_download_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, help_text='Obligatorio solo si el producto es descargable', null=True, upload_to='store/products/to_download/{name}'),
        ),
    ]
