# Generated by Django 4.2.7 on 2025-12-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_is_downloadable_product_is_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
