# Generated by Django 4.2.7 on 2025-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='verification_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
