# Generated by Django 4.2.7 on 2025-12-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
