# Generated by Django 4.2.7 on 2025-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='PayPal', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
    ]
