# Generated by Django 4.2.7 on 2025-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_payment_method_alter_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID único de la transacción generado por el proveedor de pago (ej. PayPal ID).', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('MANUAL', 'Aprobación Manual/Crédito')], default='PAYPAL', help_text='Método de pago utilizado para la orden.', max_length=50),
        ),
    ]
