# Generated by Django 4.2.7 on 2025-12-03 10:02

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, help_text='Obligatorio solo si el producto es descargable', null=True, upload_to=store.models.Product.get_download_file),
        ),
    ]
