# Generated by Django 4.2.7 on 2025-12-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_download_file_product_is_downloadable_and_more'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_record', to='store.orderitem'),
        ),
    ]
