# Generated by Django 4.2.17 on 2024-12-27 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keymoments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('excerpt', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=keymoments.models.KeyMoment.get_image_path)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('moment_type', models.CharField(choices=[('SOCIAL', (('birth', 'Birth'), ('death', 'End'), ('love', 'Love'), ('moving', 'Moving'))), ('ACADEMIC', (('school', 'School'), ('college', 'College'), ('institute', 'Institutes'), ('self', 'Self Learned'))), ('WORK', (('hired', 'Hired'), ('fired', 'Fired'), ('own', 'Own Bussiness'), ('gig', 'Independent'))), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('likes', models.ManyToManyField(blank=True, related_name='moment_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Key Moments',
                'ordering': ['-start_date'],
            },
        ),
    ]
